[package]
name = "xswezan/superattribute"
description = "Easier Attributes with Private and ReadOnly attributes"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Janitor = "howmanysmall/janitor@1.15.1"